name: Inventario Compile

on: workflow_call

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Compile project
      working-directory: ./InventarioCRUD
      run: mvn clean compile
      
    - name: Upload compiled code
      uses: actions/upload-artifact@v3
      with:
        name: inventario-compiled
        path: InventarioCRUD/target/