name: Inventario Lint

on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Download compiled code
      uses: actions/download-artifact@v3
      with:
        name: inventario-compiled
        path: InventarioCRUD/target/
        
    - name: Run Checkstyle
      working-directory: ./InventarioCRUD
      run: mvn checkstyle:check
      
    - name: Run PMD
      working-directory: ./InventarioCRUD
      run: mvn pmd:check
      
    - name: Run SpotBugs
      working-directory: ./InventarioCRUD
      run: mvn spotbugs:check