name: Análisis de Calidad de Código
run-name: Lint 

on:
  push:

jobs:
  lint:
    name: Ejecutar análisis estático
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Ejecutar Checkstyle (sin fallar)
      working-directory: ./InventarioCRUD
      run: |
        mvn checkstyle:check -Dcheckstyle.failOnViolation=false || echo "Checkstyle encontró problemas pero continuamos"
        
    - name: Ejecutar PMD
      working-directory: ./InventarioCRUD
      run: |
        mvn pmd:pmd -Dpmd.failOnViolation=false || echo "PMD encontró problemas pero continuamos"
        
    - name: Ejecutar SpotBugs
      working-directory: ./InventarioCRUD
      run: |
        mvn spotbugs:check -Dspotbugs.failOnError=false || echo "SpotBugs encontró problemas pero continuamos"
      
    - name: Subir reportes
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lint-reports
        path: |
          InventarioCRUD/target/checkstyle-result.xml
          InventarioCRUD/target/pmd.xml
          InventarioCRUD/target/spotbugsXml.xml
        retention-days: 1